os: osx
language: python
dist: xenial
sudo: true
before_install:
  - brew tap bytom/bytom && brew install bytom
install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install -y python$TRAVIS_PYTHON_VERSION-dev
  - pip install -r test-requirements.txt
  - pip install tox-travis coveralls
matrix:
  include:
  - name: '2.7'
    python: 2.7
  - name: '3.7'
    python: 3.7
before_script:
  - bytomd node > /dev/null &
  - sleep 5
script:
  - tox
after_success: if [ "${TRAVIS_PYTHON_VERSION}" == "3.7" ]; then coveralls; fi;